name: Kinesis Bridge CI

on:
  push:
    branches: [mainnet]
  pull_request: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Pact
        run: |
          PACT_VERSION="5.1"
          curl -LO https://github.com/kadena-io/pact-5/releases/download/$PACT_VERSION/pact-$PACT_VERSION-linux-x64.tar.gz
          mkdir -p .bin
          tar -xvzf pact-$PACT_VERSION-linux-x64.tar.gz -C .bin ./pact
          chmod +x .bin/pact

      - name: Add Pact to PATH
        run: echo "PATH=$PATH:$GITHUB_WORKSPACE/.bin" >> $GITHUB_ENV

      - name: Run tests
        working-directory: contracts
        run: bin/bash ./shell/ci.sh